#!/bin/sh
compile_all=1
if [ $compile_all -eq 1 ];then
   rm -f *.i90 *.i *.o *.mod lib*a
   mpif90 -C -traceback -real-size 64 -c ../FV3/gfsphysics/physics/machine.F
   mpif90 -C -traceback -real-size 64 -c ../FV3/gfsphysics/physics/physcons.F90
   mpif90 -C -traceback -real-size 64 -c ../FV3/gfsphysics/physics/mersenne_twister.f
   mpif90 -C -traceback -I../FMS/include -c ../FMS/platform/platform.F90
   mpif90 -C -traceback -nowarn -DGFS_PHYS -I../FMS/include -c ../FMS/constants/constants.F90
   mpif90 -real-size 64  -C -traceback -I../FV3/atmos_cubed_sphere -I../FMS/include -I../FMS/fv3gfs -c fv_control_stub.F90
   mpif90 -real-size 64 -traceback -I../FV3/atmos_cubed_sphere -I../FMS/include -I../FMS/fv3gfs -c atmosphere_stub.F90
   mpif90 -C -traceback -real-size 64 -c standalone_stochy_module.F90
   mpif90 -C -traceback -real-size 64 -c stochy_namelist_def_new.F90
   mpif90 -C -DSTOCHY_UNIT_TEST -traceback -real-size 64 -I../FMS/fv3gfs -c stochy_patterngenerator_new.F90
   mpif90 -C -DSTOCHY_UNIT_TEST -traceback -real-size 64 -I../FMS/fv3gfs -I/scratch2/BMC/gsienkf/Philip.Pegion/NEMSfv3gfs_develop/FMS/FMS_INSTALL -I../FV3/atmos_cubed_sphere -c stochastic_physics_new.F90
   ar rv libstochastic_physics_new.a *.o
fi
mpif90 -traceback -real-size 64 -qopenmp -o standalone_stochy_new standalone_stochy_new.F90 -I../FV3/atmos_cubed_sphere -I../FMS/FMS_INSTALL -I/apps/netcdf/4.7.0/intel/18.0.5.274/include -L. -lstochastic_physics_new -L../FV3/atmos_cubed_sphere -lfv3core -L../FMS/FMS_INSTALL -lfms -L../FV3/gfsphysics -lgfsphys -L/scratch2/NCEPDEV/nwprod/NCEPLIBS/compilers/intel/18.0.5.274/lib -lsp_v2.0.3_d -L/scratch1/NCEPDEV/nems/emc.nemspara/soft/esmf/8.0.0bs48-intel18.0.5.274-impi2018.0.4-netcdf4.6.1/lib -Wl,-rpath,/scratch1/NCEPDEV/nems/emc.nemspara/soft/esmf/8.0.0bs48-intel18.0.5.274-impi2018.0.4-netcdf4.6.1/lib -lesmf -L/apps/netcdf/4.7.0/intel/18.0.5.274/lib -lnetcdff -lnetcdf
